name: flood_prediction_fyp
description: "FYP Project enhancement with state_management"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  gif_view: ^1.0.0
  go_router: ^16.0.0
  hydrated_bloc: ^10.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.15  
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^3.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - assets/gif/
